import { pageLabel } from "../shared/page-label";
import { captureButton } from "./curation";
import "./digest.css";
type Api = (path: string) => Promise<any>;
const esc = (s: unknown) =>
  String(s ?? "").replace(
    /[&<>"']/g,
    (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        c
      ]!,
  );
const day = (n: number) =>
  new Date(n).toLocaleDateString("zh-TW", {
    month: "numeric",
    day: "numeric",
    weekday: "short",
  });
const clock = (n: number) =>
  new Date(n).toLocaleTimeString("zh-TW", {
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
const outcome: Record<string, string> = {
  open: "還沒收尾",
  done: "看起來完成",
  browse: "閒逛",
  unclear: "",
};
// Session page lists stay compact; only pages cited on their own get the capture button.
const link = (p: { url: string; title: string }, capture = true) =>
  `<a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${esc(pageLabel(p).title)}</a>${capture && location.protocol.startsWith("http") ? captureButton({ url: p.url, title: p.title || p.url }) : ""}`;
function ref(r: any) {
  if (!r) return "";
  if (r.kind === "page")
    return `<li>${link(r)}<small>本期 ${r.days} 天${r.earlierMonths.length ? `，更早在 ${esc(r.earlierMonths.join("、"))} 看過` : ""}</small></li>`;
  return `<li><strong>${day(r.start)} ${clock(r.start)}–${clock(r.end)}</strong> ${esc(r.activity)}${outcome[r.outcome] ? ` <span class="digest-tag">${outcome[r.outcome]}</span>` : ""}<details><summary>${r.total} 個頁面${r.total > r.pages.length ? `（顯示前 ${r.pages.length} 個）` : ""}</summary><ol>${r.pages.map((p: any) => `<li>${link(p, false)}</li>`).join("")}</ol></details></li>`;
}
const evidence = (ids: string[], refs: Record<string, any>) =>
  ids.length
    ? `<details class="insight-evidence"><summary>查看依據（${ids.length}）</summary><ul>${ids.map((id) => ref(refs[id])).join("")}</ul></details>`
    : "";

// AI weekly digest on the overview. Generated by the scheduled job; this only reads the latest result.
export function aiDigest(api: Api) {
  const root = document.getElementById("ai-digest")!;
  async function load() {
    let d: any;
    try {
      d = (await api("/api/digest")).digest;
    } catch {
      root.hidden = true;
      return;
    }
    // Same shape as 你的瀏覽線索 below: heading, one row of cards, the rest folded away.
    root.hidden = !d;
    if (!d) return;
    const card = (label: string, title: string, text: string, ids: string[]) =>
      `<article><small>${label}</small><h3>${esc(title)}</h3><p>${esc(text)}</p>${evidence(ids, d.refs)}</article>`;
    const observations = d.observations.map((o: any) =>
      card("本週觀察", o.title, o.text, o.evidence),
    );
    const threads = d.threads.map((t: any) =>
      card("值得繼續", t.title, t.why, t.evidence),
    );
    const rest = [...observations.slice(3), ...threads];
    root.innerHTML = `<div class="section-heading"><div><h2>本週回顧</h2><p>${esc(d.headline)}</p></div></div><div class="personal-cards">${observations.slice(0, 3).join("")}</div>
${rest.length ? `<details class="digest-more"><summary>其餘 ${observations.length > 3 ? `${observations.length - 3} 則觀察、` : ""}${threads.length} 條值得繼續的線索</summary><div class="personal-cards">${rest.join("")}</div></details>` : ""}
<p class="method-note">${day(d.from)}—${day(d.to - 1)} · ${d.stats.visits.toLocaleString()} 次造訪 · 想問你：${esc(d.question)}<br>由 ${esc(d.models.classifier)} 分類、${esc(d.models.interpreter)} 解讀，只依標題與網址推測；每天 08:00 有新紀錄時更新。</p>`;
  }
  return { load };
}
